import numpy as np
import os
import tensorflow as tf
from keras.models import load_model
import sys

current_directory = os.path.dirname(os.path.abspath(__file__))
parent_directory = os.path.dirname(current_directory)
gan_directory = os.path.join(parent_directory, 'GAN')
sys.path.append(gan_directory)

from gan import wasserstein_loss

current_dir = os.path.dirname(os.path.abspath(__file__))

generator_path = os.path.join(gan_directory, 'models/generator_model20.keras')

def generate_packet_by_gan():
    '''Generate packets using GAN
    
    Returns:
        packet: Generated packet
    '''
    generator = load_model(generator_path, custom_objects={'wasserstein_loss': wasserstein_loss})

    noise = np.random.normal(0.0, 1.0, (1, 1024))

    generated_image = generator.predict(noise)

    generated_image = (generated_image + 1) * 127.5
    packet = generated_image.astype(np.uint8)
            
    print("Packets generated by GAN!")
    
    return packet