from curses import raw
import os
import numpy as np

current_dir = os.path.dirname(os.path.abspath(__file__))
generated_packets_dir = os.path.join(current_dir, 'generated_ip_packets_by_gan')

d = 2
w = 16
n = 28
n_meios = int(n / d)

def decode_packets(raw_bytes):
    '''Decode the packets generated by GAN
    
    Args:
        raw_bytes (numpy.ndarray): Raw bytes of the generated packets
        
    Returns:
        ipv4, protocol: A tuple with the IPv4 header and the protocol header
    '''    
    packet = np.zeros((n_meios, n_meios), dtype=np.uint8)
    
    raw_bytes = np.array(raw_bytes).reshape((n, n))

    for i in range(0, n, d):
        for j in range(0, n, d):
            packet[int(i/2), int(j/2)] = int(raw_bytes[i:i+d, j:j+d].mean())
    
    packet_in_list = []
    
    for i in range(0, n_meios, 1):
        for j in range(0, n_meios, d):
            packet_in_list.append((str(hex(int(packet[i][j] / 16)).replace('0x', '')) + str(hex(int(packet[i][j+1] / 16)).replace('0x', ''))))

    ipv4 = packet_in_list[0:20]
    protocol = packet_in_list[20:84]

    ipv4 = ''.join(ipv4)
    protocol = ''.join(protocol)
        
    return ipv4, protocol